"""
LLM Alpha 挖掘 (P2) — 用大语言模型生成 Alpha 因子表达式。

参考论文: CogAlpha (2511.18850) + Alpha-R1 (2512.23515)
核心思路: LLM 推理生成因子表达式 → 遗传算法筛选 → 回测验证

当前实现: 模板化因子生成器（无需 LLM API）+ IC/IR 筛选
完整 LLM: 需接入 OpenAI/Claude API 自动生成 RPN 表达式
"""

import logging
import numpy as np
import pandas as pd
from core.indicators import rsi as _rsi_impl

log = logging.getLogger(__name__)

# Pre-defined factor templates (in production, generated by LLM reasoning)
ALPHA_TEMPLATES = [
    # Format: (name, formula_description)
    ("ts_mean_ret_5d", "5-day moving average of daily returns"),
    ("ts_std_ret_21d", "21-day rolling standard deviation of returns"),
    ("ts_corr_price_vol", "correlation between price and volume over 63 days"),
    ("ts_rank_ret_21d", "cross-sectional rank of 21-day returns"),
    ("ts_delta_close_ma50", "close / MA(50) - 1"),
    ("ts_delta_close_ma200", "close / MA(200) - 1"),
    ("ts_vol_price_regression", "residual of regressing volume on price over 21d"),
    ("ts_macd_divergence", "MACD(12,26) histogram / close"),
    ("ts_bollinger_breakout", "abs(close - MA(20)) / (2 * std(20))"),
    ("ts_rsi_reversal", "(RSI(14) - 50) / 50"),
    ("ts_alpha_101_style", "rank(ts_mean(close, 5) - ts_mean(close, 20))"),
    ("ts_alpha_momentum_crash", "(ret_1d - ret_21d) / (std_21d + eps)"),
]


class LLMAlphaMiner:
    """Alpha factor generator with IC/IR evaluation."""

    def __init__(self, top_k=10):
        self.top_k = top_k
        self._factors: dict[str, pd.Series] = {}
        self._ic_scores: dict[str, float] = {}

    def generate_factors(self, df: pd.DataFrame) -> pd.DataFrame:
        """
        Generate alpha factors from OHLCV data.

        Returns:
            DataFrame with all factor values, same index as input.
        """
        close = df["close"].astype(float)
        volume = df["volume"].astype(float)
        returns = close.pct_change()

        factors = pd.DataFrame(index=df.index)

        # ts_mean_ret_5d
        factors["mean_ret_5d"] = returns.rolling(5).mean()

        # ts_std_ret_21d
        factors["std_ret_21d"] = returns.rolling(21).std()

        # ts_corr_price_vol
        factors["corr_price_vol"] = close.rolling(63).corr(volume)

        # ts_rank_ret_21d
        factors["rank_ret_21d"] = close.pct_change(21).rank(pct=True)

        # ts_delta_close_ma50
        factors["delta_ma50"] = close / close.rolling(50).mean() - 1

        # ts_delta_close_ma200
        factors["delta_ma200"] = close / close.rolling(200).mean() - 1

        # ts_vol_price_regression (simplified: vol ratio)
        factors["vol_price_resid"] = (volume / volume.rolling(21).mean() -
                                       close / close.rolling(21).mean())

        # ts_macd_divergence
        ema12 = close.ewm(span=12, adjust=False).mean()
        ema26 = close.ewm(span=26, adjust=False).mean()
        factors["macd_div"] = (ema12 - ema26) / (close + 1e-8)

        # ts_bollinger_breakout
        bb_std = close.rolling(20).std()
        factors["bb_break"] = abs(close - close.rolling(20).mean()) / (2 * bb_std + 1e-8)

        # ts_rsi_reversal
        factors["rsi_rev"] = (_rsi_impl(close, 14) - 50) / 50

        # ts_alpha_101_style
        factors["alpha_101"] = (close.rolling(5).mean() / close.rolling(20).mean() - 1).rank(pct=True)

        # ts_alpha_momentum_crash
        factors["mom_crash"] = (close.pct_change() - close.pct_change(21)) / (returns.rolling(21).std() + 1e-8)

        factors.dropna(inplace=True)
        return factors

    def evaluate_ic(self, factors: pd.DataFrame, forward_returns: pd.Series):
        """Compute Information Coefficient (rank correlation) for each factor."""
        common_idx = factors.index.intersection(forward_returns.dropna().index)
        for col in factors.columns:
            f = factors[col].loc[common_idx]
            r = forward_returns.loc[common_idx]
            valid = ~(f.isna() | r.isna())
            if valid.sum() < 30:
                self._ic_scores[col] = 0.0
            else:
                self._ic_scores[col] = f[valid].corr(r[valid], method="spearman")

    def select_top_factors(self) -> list[tuple[str, float]]:
        """Return top-k factors by absolute IC."""
        sorted_factors = sorted(self._ic_scores.items(),
                                key=lambda x: abs(x[1]), reverse=True)
        return sorted_factors[:self.top_k]
